call pathogen#runtime_prepend_subdirectories(expand('~/.vimbundles'))

set nocompatible        " enable VIM features
set ch=1
set mousehide           " hide the mouse when typing
set shiftwidth=2
set softtabstop=2
set tabstop=2
set smartindent
set expandtab
set ruler
set ai
set background=dark
set nobackup
set nowritebackup
set noswapfile
set bs=2
set cinoptions+=:0g0
set history=50
set gdefault
set showmatch
set matchpairs+=<:>
set showmode
set nowrap
set mouse-=a
set noincsearch
set number
set go-=rL
set wildignore+=*.o,1.8.7,.git,*.obj

" Disable all bells
set vb t_vb=""
autocmd VimEnter * set vb t_vb=
au! GuiEnter * set vb t_vb=

highlight LineNr guifg=#777777 guibg=#202020 ctermfg=grey ctermbg=darkgrey

noremap <C-J> <PageDown>
noremap <C-K> <PageUp>

syn sync fromstart

" Automatically strip whitespace when saving
"autocmd BufWritePre * :%s/\s\+$//e
"autocmd BufWritePre * :%s/\r//e

if has("gui_running")
  set guifont=Inconsolata:h14
  set showtabline=2
  set guioptions-=T
  set background=light
  colorscheme github
else
  colorscheme fruity
endif

if has("autocmd")
  filetype plugin indent on
endif

syntax on
let c_syntax_for_h = 1
let g:netrw_ftpmode = "binary"
let g:netrw_win95ftp = 0
let g:asmsyntax = "nasm"

" Show end of line whitespace as an error
match ErrorMsg / \+$/

" Copy & paste
vmap <C-c> :w! ~/.vbuf<CR>
nmap <C-c> :.w! ~/.vbuf<CR>
nmap <C-v> :r ~/.vbuf<CR>

" Key support
map!  <BackSpace>
map ; :

" Whitespace cleaning and saving
vmap <C-o> :s/\s\+$//e<CR>:s/\r//e<CR>:s/\t/  /e<CR>:w<CR>
nmap <C-o> :%s/\s\+$//e<CR>:%s/\r//e<CR>:%s/\t/  /e<CR>:w<CR>

" Navigation
nmap <C-n> :qa!<CR>
nmap <C-m> :n<CR>
nmap <C-y> :NERDTreeToggle<CR>
nmap <C-u> :NERDTreeMirror<CR>
nmap <C-i> :NERDTreeFind<CR>
nmap <C-t> :CommandT<CR>
nmap <S-t> :CommandTFlush<CR>

let Tlist_Use_Right_Window = 1
let Tlist_Show_One_File = 1

augroup mkd
  autocmd BufRead *.mkd set ai formatoptions=tcroqn2 comments=n:>
augroup END

autocmd BufNewFile,BufRead *.lib set filetype=c
autocmd BufEnter * stopinsert
