#!/usr/bin/env ruby

require "shellwords"

DESTINATION_PATH = Shellwords.escape(ARGV.pop)
SOURCE_PATHS     = ARGV.map { |p| Shellwords.escape p }.join(" ")

OPTIONS = %w(
  archive
  verbose
  compress
  rsh=ssh
  delete-after
  delete-excluded
).map { |opt| "--#{opt}" }.join(" ")

EXCLUSIONS = %w(
  .DS_Store
  Downloads
  Dropbox
  Library/Caches
).map { |opt| "--exclude=#{opt}" }.join(" ")

COMMAND = "rsync #{OPTIONS} #{EXCLUSIONS} #{SOURCE_PATHS} #{DESTINATION_PATH}"

puts COMMAND
system COMMAND
